apiVersion: apps/v1
kind: Deployment
metadata:
  name: Jones 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Jones
  template:
    metadata:
      labels:
        app: Jones
    spec:
      containers:
      - image: okteto.dev/Jones:latest
        name: Jones
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "7e1bca05-e868-4c63-8fed-b2e8e644e698"
        - name: Vless_Path
          value: "/vl33bbs5"
        - name: Vmess_UUID
          value: "7e1bca05-e868-4c63-8fed-b2e8e644e698"
        - name: Vmess_Path
          value: "/vm66vv3346"
        - name: Share_Path
          value: "/v2link"
