apiVersion: v1
kind: Service
metadata:
  name: Jones 
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "Jones "
    port: 8080
  selector:
    app: Jones 
